import 'gulp-ng-recipes/dist/globals';
import 'gulp-ng-recipes/dist/server';
import 'gulp-ng-recipes/dist/typescript';
import 'gulp-ng-recipes/dist/sass';
import 'gulp-ng-recipes/dist/images';
import 'gulp-ng-recipes/dist/fonts';
import 'gulp-ng-recipes/dist/offline';
import 'gulp-ng-recipes/dist/build';
import 'gulp-ng-recipes/dist/gpdeploy';
